let message = "Hello world";
console.log(message);
message = "Good night world";
console.log(message);
let n = 123;
console.log(n);
let str1 = "Hello";
console.log(str1);
let str2 = 'Hello world';
console.log(str2);
let str3 = `${str1} world`;
console.log(str3);
let bool1 = true;
let bool2 = false;
console.log(bool1);
console.log(bool2);
let name = null;
console.log(name);
console.log(typeof 20);
console.log(typeof "str");
console.log(typeof true);
console.log(typeof undefined);
let bool = true;
console.log(typeof bool);
let str = String(bool);
console.log(typeof str);
console.log(Boolean(1));
console.log(Boolean(0));
console.log(Boolean("hello"));
console.log(Boolean(""));
let say = "Hello";
console.log(say);
let add = 6 + 2;
console.log(add);
let sub = 6 - 2;
console.log(sub);
let mul = 6 * 2;
console.log(mul);